version: 2.0

shared_config: &shared_config
  working_directory: ~/workspace
  docker:
    - image: circleci/python:3.7.7
      environment:
        PIPENV_VENV_IN_PROJECT: true

jobs:
  checkout:
    <<: *shared_config
    steps:
      - checkout
      - attach_workspace:
          at: ~/workspace
      - persist_to_workspace:
          root: ~/workspace
          paths: .
  publish:
    <<: *shared_config
    steps:
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Update apt
          command: |
            sudo apt-get -y -qq update
      - run:
          name: Install Pipenv
          command: |
            sudo apt-get -y -qq install python-dev python-pip
            sudo pip install pipenv --upgrade
      - run:
          name: Pipenv Install (with dev dependencies)
          command: |
            pipenv --three
            pipenv install -d
      - run:
          name: Distribute
          command: |
            mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
            AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID}" \
            AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY}" \
            pipenv run publish "pip.aaronmamparo.com"
workflows:
  version: 2
  checkout-deploy:
    jobs:
      - checkout:
          filters:
            branches:
              only:
                - master
      - publish:
          context:
            - AWS
          requires:
            - checkout