version: 2.0

shared_config: &shared_config
  working_directory: ~/workspace
  docker:
    - image: circleci/python:3.7.7
      environment:
        PIPENV_VENV_IN_PROJECT: true

update_apt: &update_apt
  name: Update apt
  command: |
    sudo apt-get -y -qq update
install_aws_cdk: &install_aws_cdk
  name: Install AWS CDK
  command: |
    curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
    sudo apt-get -y -qq install nodejs
    sudo npm i -g aws-cdk
install_pipenv: &install_pipenv
  name: Install Pipenv
  command: |
    sudo apt-get -y -qq install python-dev python-pip
    sudo pip install pipenv --upgrade
pipenv_install: &pipenv_install
  name: Pipenv Install (with dev dependencies)
  command: |
    pipenv --three
    pipenv install -d

jobs:
  checkout:
    <<: *shared_config
    steps:
      - checkout
      - attach_workspace:
          at: ~/workspace
      - persist_to_workspace:
          root: ~/workspace
          paths: .
  deploy_python_package:
    <<: *shared_config
    steps:
      - attach_workspace:
          at: ~/workspace
      - run:
          <<: *update_apt
      - run:
          <<: *install_pipenv
      - run:
          <<: *pipenv_install
      - add_ssh_keys:
          fingerprints:
            - "c2:f2:41:34:77:ac:31:ff:2c:3a:2a:1e:96:a9:ac:85"
      - run:
          name: Distribute
          command: |
            distribute()
            {
              pipenv run pipenv-setup sync
              AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID}" \
              AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY}" \
              AWS_DEFAULT_REGION="us-east-1" \
              pipenv run s3pypi --bucket "pypi-repository-bucket" --verbose
            }

            bump_version_number_and_push()
            {
              git reset --hard HEAD
              git config --global user.email "bumpversion@circleci.com"
              git config --global user.name "bumpversion"
              echo "Bumping version"
              pipenv run bumpversion \
                --current-version "$(pipenv run python setup.py --version)" \
                --verbose --commit --tag \
                --message "Bump version: {current_version} → {new_version} [skip ci]" \
                patch setup.py
              echo "Pushing"
              yes | git push
            }

            {
              distribute
            } || {
              bump_version_number_and_push
              distribute
            }
  deploy_stack:
    <<: *shared_config
    steps:
      - attach_workspace:
          at: ~/workspace
      - setup_remote_docker
      - run:
          <<: *update_apt
      - run:
          <<: *install_pipenv
      - run:
          <<: *pipenv_install
      - run:
          <<: *install_aws_cdk
      - run:
          name: Deploy stack
          command: |
            AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID}" \
            AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY}" \
            AWS_DEFAULT_REGION="us-east-1" \
            cdk deploy --require-approval never --verbose
workflows:
  version: 2
  checkout-deploy:
    jobs:
      - checkout:
          filters:
            branches:
              only:
                - master
      - deploy_python_package:
          requires:
            - checkout
      - deploy_stack:
          requires:
            - checkout